kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-csi-toly
  uid: 48ecd668-140b-4b3b-aed8-a66eb5524634
  resourceVersion: '874791'
  creationTimestamp: '2024-04-12T21:45:35Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'false'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2024-04-12T21:48:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:storageclass.kubernetes.io/is-default-class': {}
        'f:parameters':
          .: {}
          'f:skuname': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate

